import type { Metadata } from "next";
import "./globals.css";
import { Poppins } from 'next/font/google';
import { DarkModeProvider } from './context/DarkModeContext';

const poppins = Poppins({ 
  weight: ['500', '700', '800'], 
  subsets: ['latin'], 
  variable: '--font-poppins' 
});

export const metadata: Metadata = {
  title: "Social Media",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${poppins.variable} antialiased`}
      >
        <DarkModeProvider>
          {children}
        </DarkModeProvider>
      </body>
    </html>
  );
}
